# Stage 1: build seeder
FROM golang:1.24.6 AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .

# Build seeder binary
RUN CGO_ENABLED=0 GOOS=linux go build -o /seed ./services/userservice/seed/seed.go


# Stage 2: runtime
FROM alpine:3.18
RUN apk add --no-cache ca-certificates

COPY --from=builder /seed /usr/local/bin/seed
COPY services/userservice/seed/users.json /seed/users.json 

CMD ["/usr/local/bin/seed"]
