basePath: /
host: localhost:8081
info:
  contact: {}
  description: User Management Service
  title: User Service API
  version: "1.0"
paths: {}
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
